# Generated by Django 5.0.7 on 2024-09-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='lyrics',
            field=models.FileField(upload_to='lyrics/'),
        ),
    ]
