# Generated by Django 5.0.7 on 2024-09-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_music_lyrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='info',
        ),
        migrations.AddField(
            model_name='user',
            name='info',
            field=models.TextField(blank=True),
        ),
    ]
