# Generated by Django 5.0.7 on 2024-09-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_music_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='is_single',
            field=models.BooleanField(default=False),
        ),
    ]
