# Generated by Django 5.0.7 on 2024-09-07 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_music_is_single'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_musics', to='music.album'),
        ),
        migrations.AlterField(
            model_name='music',
            name='played_before',
            field=models.ManyToManyField(blank=True, related_name='musics_played_before', to='music.user'),
        ),
    ]
