# Generated by Django 5.0.7 on 2024-09-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_music_album_alter_music_played_before'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_creator',
            field=models.BooleanField(default=False),
        ),
    ]
