# Generated by Django 5.0.7 on 2024-09-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_alter_collection_owner_alter_playlist_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='playlist',
            name='image',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
